export interface ProgramData {
    id: number,
    programName: string,
    programDescription: string,
    duration: string,
    applicationFee: number,
    tutionFee: number,
    levelOfEducation: string,
    status: string,
    subjectRequirements: string,
    academicRequirements: string,
    programCategoryId: number,
    programIntake: number,
    intakeId: number,
    instituteId: number,
    noOfIntake?:string,
    programCategoryName?:string,
    courseTypeName?:string,
    instituteName?:string,
    sessionName?:string  
}
