export interface ProgramData {
    id: number,
    programName: string,
    programDescription: string,
    duration: string,
    applicationFee: number,
    tutionFee: number,
    levelOfEducation: string,
    status: string,
    subjectRequirements: string,
    academicRequirements: string,
    programCategoryId: number,
    programIntake: number,
    courseTypeId:number,
    courseTypeName:string,
    consultancyId:number,
    intakeId: number,
    instituteId: number,
    noOfIntake:string,
    programCategoryName:string,
    instituteName:string,
    sessionName:string,
    sessionId:number,
    isPublic:boolean,  
}
